### ISSUE TITLE
Training Batch Setting Issue

### ISSUE THREAD

**Issue by debrekXuHan** [jackie840129/STE-NVAN#3]
In run_NL.sh script, default batch setting is "--class_per_batch 8 --track_per_class 4 --S 8". When I used single GPU 1080Ti (11GB) to train model with default setting, I encountered GPU out of memory problem. 
(1) If I set class_per_batch or S smaller, the accuracy will be decreased a lot? 
(2) It seems that 1080Ti cannot support default setting training task. Which GPU model did you use?

**Comment by jackie840129** [comment]
1. I use two TeslaV100 for training Non-local version. If you use the baseline version, it will cost about 22G~23G (two Titan Xp).
2. Because you can count that in every batch we will have 8x4x8=256 images, so it is impossible to use only one GPU. If you use two 1080Ti for parallel training, maybe you can use "--class_per_batch 8 --track_per_class 3 --S 6"
3. For performance, reducing S to 6 will slightly degrade the performance. I think the class_per_batch is important.

**Comment by debrekXuHan** [comment]
@jackie840129 Appreciate a lot for your reply.
